language: generic
dist: bionic
services:
- docker
script:
- make
- make quirks
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  target_branch: gh-pages
env:
  global:
    secure: AFf1vz3fVzJs/z691fouMKa+XxZP3jiPElOZLL1CCnmkuqTvXr46PJJgyjXTeNQuyZi9U8c2ORorfIQlzMOIsbpuS1oHcd4/dWmZvtYi0JV5qGuf1qahVhEi99YZzTQJ/q9Ic6umGl7PRNPSbHjvp3H3GPPjU8SIXd0wvCrXki0kOo3yHFYqc8WESsXFxfzMmRWqq0HabLdmarJDlPjGRcKiTYcZn2OeHQM+7kEAvI88UUxD9JhEJZhNcvGU0vyz1A7UjWsLY0P7KtU9qikQP6EfgIao8YPTPoiEN9bgF0GauhtOMSi7H/ek92XBbuFCYFJwloaVc8CVqzG7DHNs0LsxtmX6oZxlgjUv5mG8cCV7jZvpLDh7lXpkBlfyS9N86kyXEZbfW4CSIh4hhqbrg/wBIFE5emaV43eoQCBhZGKXZg/HF2LrWfWjxvmTKTWkLjyJwZTh3c6pdLJdv9IAsaRFRNYl5nyXVSrAp7IEixHXZy/KpQSOZ/mldtLvA73UwtK531C95i+XCleJ3lUX6cGy0t8bk+3wbNIMUqZcYxdkR2cVD2d2vf15OG3bvkr3+6rSxgqpZdIEpSpd+1BM5LEKr7EsrqQ/9Vt4X4yji8p//jLehPLEfS7c+gyIMScATAuIV3zZdZo5Nmx0ToZ1ZxX4lzPxQfhECdQBl5tDFbw=
