#!/bin/bash

#set -x
set -e

if [ "$#" -ge 1 ];then
  IFS=',' read -ra FORMATS <<< "$@"
else
  FORMATS=(html pdf epub docx odt pptx revealjs dzslides plain)
fi
# See https://www.garrickadenbuie.com/blog/pandoc-syntax-highlighting-examples/
# for highlight style samples
# builtin styles:
# pygments tango espresso zenburn kate
# monochrome breezedark haddock
CODE_HIGHLIGHT_STYLE=tango

BIB_FORMAT_CSL=ieee-with-url

# This will generate speech translations. See
#   audio/README.md
EMBED_AUDIO=true

# See pandoc documentation
# https://pandoc.org/MANUAL.html
# for more details if you want to tweak
pandoc_build()
{

  format=$1

  docs="docs/*.md"

  if [ "${EMBED_AUDIO}" = true ]; then
     docs="tmp/*.md"
     mkdir -p tmp
     for file in docs/*.md; do
        audio_str=$(cat << EOF
<audio controls="1"> <source src="audio/mp3/$(basename $file).plain.mp3" type="audio/mpeg"></source> </audio>
EOF
)
       sed "0,/^\\(#.*\\)$/s//\\1\\n$(echo $audio_str | sed 's;/;\\/;g')/" $file > tmp/$(basename $file)
     done
  fi

  echo "Generating ${format}"

  # FIXME can this be DRYed up a bit?
  if [ "${format}" == "html" ];then
    pandoc ${docs} --toc \
      --self-contained \
      --top-level-division=chapter \
      --metadata date="$( date +'%D %X %Z')" \
      --metadata link-citations=true \
      --bibliography=bibliography.yaml \
      --csl "${BIB_FORMAT_CSL}.csl" \
      --template=./templates/GitHub.html5 \
      --filter pandoc-crossref \
      --filter pandoc-citeproc \
      --filter pandoc-include-code -s --highlight-style ${CODE_HIGHLIGHT_STYLE} \
      -o output/doc.${format}

  elif [ "${format}" == "pdf" ];then
    pandoc ${docs} --toc \
      --top-level-division=chapter \
      --metadata date="$( date +'%D %X %Z')" \
      --metadata link-citations=true \
      --bibliography=bibliography.yaml \
      --csl "${BIB_FORMAT_CSL}.csl" \
      --filter pandoc-crossref \
      --filter pandoc-citeproc \
      --filter pandoc-include-code -s --highlight-style ${CODE_HIGHLIGHT_STYLE} \
      -o output/doc.${format}
  elif [ "${format}" == "plain" ];then
     mkdir -p output/plain
     for file in ${docs}; do
        pandoc $file \
          -t ${format} \
          --filter pandoc-crossref \
          -o "output/plain/$(basename $file).plain"
     done
  elif [ "${format}" == "revealjs" ] || [ "${format}" == "dzslides" ];then
    mkdir -p output/js/${format}

    for file in ${docs}; do
      work_file="/tmp/$(basename $file).tmp"

      cat ${file} | \
        vim -E '+%s/^[\^\d\+\]:\_.*' +%p -cq! /dev/stdin |\
        vim -E '+%s/\(\S\)\n\(\S\)/\1 \2/' +%p -cq! /dev/stdin | \
        vim -E '+%s/\(\S\+\_$\n\)/\1\r---\r/g' +%p -cq! /dev/stdin > ${work_file}

      pandoc ${work_file} \
        -s \
        -t ${format} \
        --slide-level 6 \
        --metadata pagetitle=$(basename $file) \
        --variable revealjs-url=https://revealjs.com \
        --metadata date="$( date +'%D %X %Z')" \
        --metadata link-citations=true \
        --bibliography=bibliography.yaml \
        --csl "${BIB_FORMAT_CSL}.csl" \
        --filter pandoc-crossref \
        --filter pandoc-citeproc \
        --filter pandoc-include-code -s --highlight-style ${CODE_HIGHLIGHT_STYLE} \
        -o "output/js/${format}/$(basename $file).html"
     done
  elif [ "${format}" == "pptx" ];then
     mkdir -p output/pptx
     for file in ${docs}; do

        work_file="/tmp/$(basename $file).tmp"

        cat ${file} | \
          vim -E '+%s/^[\^\d\+\]:\_.*' +%p -cq! /dev/stdin |\
          vim -E '+%s/\(\S\)\n\(\S\)/\1 \2/' +%p -cq! /dev/stdin | \
          vim -E '+%s/\(\S\+\_$\n\)/\1\r---\r/g' +%p -cq! /dev/stdin > ${work_file}
        #cat $file | \
        #  vim -E '+%s/\(\S\+\)\n\(\S\+\)/\1 \2/' +%p -cq! /dev/stdin | \
        #  vim -E '+%s/^[\^\d\+\]:.*' +%p -cq! /dev/stdin | \
        #  vim -E '+%s/\(\S\+\)\n/\1\r\r-----\r/g' +%p -cq! /dev/stdin |\
        #  tee $work_file
        pandoc ${work_file} \
          -t ${format} \
          --slide-level 6 \
          --metadata date="$( date +'%D %X %Z')" \
          --metadata link-citations=true \
          --bibliography=bibliography.yaml \
          --csl "${BIB_FORMAT_CSL}.csl" \
          --filter pandoc-crossref \
          --filter pandoc-citeproc \
          --filter pandoc-include-code -s --highlight-style ${CODE_HIGHLIGHT_STYLE} \
          -o "output/pptx/$(basename $file).pptx_part"
     done
  else
     pandoc ${docs} --toc \
      --top-level-division=chapter \
      --metadata date="$( date +'%D %X %Z')" \
      --metadata link-citations=true \
      --bibliography=bibliography.yaml \
      --csl "${BIB_FORMAT_CSL}.csl" \
      -t ${format} \
      --filter pandoc-crossref \
      --filter pandoc-citeproc \
      --filter pandoc-include-code -s --highlight-style ${CODE_HIGHLIGHT_STYLE} \
      -o output/doc.${format}
  fi
}

mkdir -p output

for format in "${FORMATS[@]}";do
  time pandoc_build ${format}
done
